### ISSUE TITLE
Error on setting order size

### ISSUE THREAD

**Issue by Lemmod** [motorback/motorBackTV#1]
When trying to get data from an Backtester the script keeps stalling at 

[2021-07-13 19:46:02] Setting Order Size...1.0
[2021-07-13 19:46:14] ERROR 17: Element Search Time Out Error On Try: 1 of 10

When I watch the progress in Chrome it keeps stuck on the Order Size setting, it seems it can't find the right setting. Using the default test settings as provided.

See attached full log. 
Uses [debug.txt](https://github.com/motorback/motorBackTV/files/6810974/debug.txt)

**Comment by qtmspin** [comment]
I am getting the same error using firefox and gecko driver.

**Comment by motorback** [comment]
Hi, please check the latest release for a possible fix to the order size issue.  https://github.com/motorback/motorBackTV/releases/tag/v0.4.6_beta

I'm not able to replicate the issue on my end with the previous release and others are not experiencing the issue but the update should be able to increase the accuracy of locating the order size element.

**Comment by qtmspin** [comment]
It was working so well :)  But alas... maybe TV updated their site again.  The bot gets stuck on Change Interval.  
[2021-10-24 15:35:04] ERROR 17: Element Search Time Out Error On Try: 10 of 10
[2021-10-24 15:35:04] ERROR 11: Script Issue java.lang.NullPointerException
[2021-10-24 15:35:04] Back Test Stopping...

Do you accept donations for keeping the code running?

**Comment by motorback** [comment]
> It was working so well :) But alas... maybe TV updated their site again. The bot gets stuck on Change Interval. [2021-10-24 15:35:04] ERROR 17: Element Search Time Out Error On Try: 10 of 10 [2021-10-24 15:35:04] ERROR 11: Script Issue java.lang.NullPointerException [2021-10-24 15:35:04] Back Test Stopping...
> 
> Do you accept donations for keeping the code running?

Hi, glad to hear the program was good for you.  Yes, TV made some site updates.  I just released an update that should resolve the time change intervals.  
https://github.com/motorback/motorBackTV/releases/tag/v0.4.7_beta

Thanks for inquiring about donations.  My paypal is mrfilas18@hotmail.com, any amount will be appreciated.

**Comment by AlTheAlligator** [comment]
> 
> 
> > It was working so well :) But alas... maybe TV updated their site again. The bot gets stuck on Change Interval. [2021-10-24 15:35:04] ERROR 17: Element Search Time Out Error On Try: 10 of 10 [2021-10-24 15:35:04] ERROR 11: Script Issue java.lang.NullPointerException [2021-10-24 15:35:04] Back Test Stopping...
> > Do you accept donations for keeping the code running?
> 
> Hi, glad to hear the program was good for you. Yes, TV made some site updates. I just released an update that should resolve the time change intervals. https://github.com/motorback/motorBackTV/releases/tag/v0.4.7_beta
> 
> Thanks for inquiring about donations. My paypal is [mrfilas18@hotmail.com](mailto:mrfilas18@hotmail.com), any amount will be appreciated.

Did tradingview break this again already? I downloaded the new version (0.4.7_beta) and I am still getting stuck on change interval.

**Comment by qtmspin** [comment]
After the update, the same error occurred for me.  I realize there was a mismatched chrome driver and chrome browser.  I uninstalled all and reinstalled save versions.

**Comment by AlTheAlligator** [comment]
> 
> 
> After the update, the same error occurred for me. I realize there was a mismatched chrome driver and chrome browser. I uninstalled all and reinstalled save versions.

I had issues with chrome closing by itself, then I updated the driver and it now opens correctly. But I get the ERROR 17 when change interval comes up. Don't you get that issue at this point?

**Comment by motorback** [comment]
Hi, the latest release is still working fine for me, I'm not able to replicate the current change interval error.  Is the issue still with the program not applying the timeframe after inputting the value or does it happen before the input of the value...or does the change interval window appear at all?

If I cant replicate the error, I will find alternate elements to target that will have the same result.

Also, as an FYI, attached is a screenshot of my chrome and firefox drivers.  I'm on FireFox v93 and Chrome v94

![currentDriverBrowserVersions](https://user-images.githubusercontent.com/45340523/139564013-e97d994c-fd93-40ff-a6b3-e9c13390bd2b.PNG)

**Comment by AlTheAlligator** [comment]
> 
> 
> Hi, the latest release is still working fine for me, I'm not able to replicate the current change interval error. Is the issue still with the program not applying the timeframe after inputting the value or does it happen before the input of the value...or does the change interval window appear at all?
> 
> If I cant replicate the error, I will find alternate elements to target that will have the same result.
> 
> Also, as an FYI, attached is a screenshot of my chrome and firefox drivers. I'm on FireFox v93 and Chrome v94
> 
> ![currentDriverBrowserVersions](https://user-images.githubusercontent.com/45340523/139564013-e97d994c-fd93-40ff-a6b3-e9c13390bd2b.PNG)

Hi! I have tried both with firefox (v93 with the same version of the driver as you use) and chrome v95 with the correct driver for that version. I get stuck at the point where the input is open link shown in the screenshot. So the window appears, but it does not set the value in the interval window. So if the chart is set to 1 minute as shown in the screenshot, but my candle is set to 5 minutes, then it opens the interval window, but puts no value into it.
![image](https://user-images.githubusercontent.com/8904635/139576701-0a0e854e-8c31-4e34-80f7-c9e4292796ba.png)

I don't know if it helps you, but this is how the input element looks on the HTML
![image](https://user-images.githubusercontent.com/8904635/139576844-7fd13060-12d3-4654-9a48-c61b03c7228f.png)

**Comment by motorback** [comment]
> > Hi, the latest release is still working fine for me, I'm not able to replicate the current change interval error. Is the issue still with the program not applying the timeframe after inputting the value or does it happen before the input of the value...or does the change interval window appear at all?
> > If I cant replicate the error, I will find alternate elements to target that will have the same result.
> > Also, as an FYI, attached is a screenshot of my chrome and firefox drivers. I'm on FireFox v93 and Chrome v94
> > ![currentDriverBrowserVersions](https://user-images.githubusercontent.com/45340523/139564013-e97d994c-fd93-40ff-a6b3-e9c13390bd2b.PNG)
> 
> Hi! I have tried both with firefox (v93 with the same version of the driver as you use) and chrome v95 with the correct driver for that version. I get stuck at the point where the input is open link shown in the screenshot. So the window appears, but it does not set the value in the interval window. So if the chart is set to 1 minute as shown in the screenshot, but my candle is set to 5 minutes, then it opens the interval window, but puts no value into it. ![image](https://user-images.githubusercontent.com/8904635/139576701-0a0e854e-8c31-4e34-80f7-c9e4292796ba.png)
> 
> I don't know if it helps you, but this is how the input element looks on the HTML ![image](https://user-images.githubusercontent.com/8904635/139576844-7fd13060-12d3-4654-9a48-c61b03c7228f.png)

Hi, thanks for the extra info.  Can you provide the Xpaths ("full Xpath" and "Xpath") of the input element, see attachment.  Minor web element structure differences can cause the issue you are experiencing.  

![image](https://user-images.githubusercontent.com/45340523/139647555-e89ac5ce-7d3d-4f38-b926-55abf4c6a44f.png)

**Comment by AlTheAlligator** [comment]
> > > Hi, the latest release is still working fine for me, I'm not able to replicate the current change interval error. Is the issue still with the program not applying the timeframe after inputting the value or does it happen before the input of the value...or does the change interval window appear at all?
> > > If I cant replicate the error, I will find alternate elements to target that will have the same result.
> > > Also, as an FYI, attached is a screenshot of my chrome and firefox drivers. I'm on FireFox v93 and Chrome v94
> > > ![currentDriverBrowserVersions](https://user-images.githubusercontent.com/45340523/139564013-e97d994c-fd93-40ff-a6b3-e9c13390bd2b.PNG)
> > 
> > 
> > Hi! I have tried both with firefox (v93 with the same version of the driver as you use) and chrome v95 with the correct driver for that version. I get stuck at the point where the input is open link shown in the screenshot. So the window appears, but it does not set the value in the interval window. So if the chart is set to 1 minute as shown in the screenshot, but my candle is set to 5 minutes, then it opens the interval window, but puts no value into it. ![image](https://user-images.githubusercontent.com/8904635/139576701-0a0e854e-8c31-4e34-80f7-c9e4292796ba.png)
> > I don't know if it helps you, but this is how the input element looks on the HTML ![image](https://user-images.githubusercontent.com/8904635/139576844-7fd13060-12d3-4654-9a48-c61b03c7228f.png)
> 
> Hi, thanks for the extra info. Can you provide the Xpaths ("full Xpath" and "Xpath") of the input element, see attachment. Minor web element structure differences can cause the issue you are experiencing.
> 
> ![image](https://user-images.githubusercontent.com/45340523/139647555-e89ac5ce-7d3d-4f38-b926-55abf4c6a44f.png)

Hi, I am not at my home PC atm, but using the work laptop, I guess it will be the same. 
The Full XPATH is /html/body/div[6]/div/div/div[1]/div/form/span/span[1]/input
The XPATH is //*[@id="overlap-manager-root"]/div/div/div[1]/div/form/span/span[1]/input
Hope this can help

**Comment by AlTheAlligator** [comment]
Just checked on my own PC, it's the same xpath there, so it should be like mentioned above

**Comment by EuclideanWild** [comment]
Any updates on this? I am having the same problem. Although on mine the bar time frame does successfully get entered and then the error message occurs.
